# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {{c:/Users/Hok Layheng/Desktop/Final_CPU/gufufuf/gufuf/cpu_risc_v_v1/Others/SEU_CSE_507_user_uart_bmpg_1.3}} [current_project]
set_property ip_output_repo {c:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/ip/RAM/dmem32word.coe}}
add_files {{C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/ip/prgrom/scenario1.coe}}
add_files {{C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/ip/prgrom/test2.coe}}
add_files {{C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/ip/prgrom/scenario2.coe}}
add_files {{C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/ip/prgrom/scenario3.coe}}
add_files {{C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/ip/prgrom/latest.coe}}
read_verilog -library xil_defaultlib {
  {C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/new/ALU.v}
  {C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/new/Clock.v}
  {C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/new/Controller.v}
  {C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/new/DataMem.v}
  {C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/new/Decoder.v}
  {C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/new/IFetch.v}
  {C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/new/Led.v}
  {C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/new/MemOrIO.v}
  {C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/new/Switch.v}
  {C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/new/Tube.v}
  {C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/new/clock_divider.v}
  {C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/new/CPU.v}
}
read_ip -quiet {{C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/ip/cpu_clk/cpu_clk.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/ip/cpu_clk/cpu_clk_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/ip/cpu_clk/cpu_clk.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/ip/cpu_clk/cpu_clk_ooc.xdc}}]

read_ip -quiet {{C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/ip/RAM/RAM.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/ip/RAM/RAM_ooc.xdc}}]

read_ip -quiet {{C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/ip/prgrom/prgrom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/constrs_1/new/const.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Hok Layheng/Desktop/Final_CPU/Final_CPU/Final_CPU.srcs/constrs_1/new/const.xdc}}]


synth_design -top CPU -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb"
